name: Build & Push Docker Image
on:
  push:
    paths:
      - 'testfolder/**'  # Trigger workflow on changes in the testfolder
  
  # Manually triggered via GitHub Actions UI (workflow dispatch)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker and build the Docker image
      - name: Build Docker image
        run: docker build -t myusername/myimage:latest testfolder/

      # Step 3: Log in to DockerHub (using secrets)
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Push the image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push myusername/myimage:latest
