name: Build & Push Docker Image

# Triggers for the workflow
on:
  push:
    paths:
      - 'testfolder/**'  # Trigger the workflow when files in testfolder change

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build Docker image (Without Buildx)
      - name: Build Docker image
        run: docker build -t rahulrv098/myimage:latest ./testfolder/

      # Step 3: Log in to DockerHub using GitHub secrets
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push rahulrv098/myimage:latest
